/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package trabalhofinalsemmvc.Veiculo;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import trabalhofinalsemmvc.utils.Marca;
import utils.Categoria;
import utils.ModeloAutomovel;
import utils.ModeloMotocicleta;
import utils.ModeloVan;

/**
 *
 * @author eduar
 */
public class TelaVenderVeiculo extends javax.swing.JPanel {

    /**
     * Creates new form TelaVenderVeiculo
     */
    VeiculoMemoria veiculoMemoria = new VeiculoMemoria();
    TelaVenderVeiculoTableModel telaVenderVenderVeiculoTableModel = new TelaVenderVeiculoTableModel();

    public TelaVenderVeiculo() {
        initComponents();
        grupoFiltroVeiculo.add(radioMarca);
        grupoFiltroVeiculo.add(radioTipo);
        grupoFiltroVeiculo.add(radioCategoria);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoFiltroVeiculo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        radioTipo = new javax.swing.JRadioButton();
        radioMarca = new javax.swing.JRadioButton();
        radioCategoria = new javax.swing.JRadioButton();
        botaofiltrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaVeiculosVender = new javax.swing.JTable();
        botaoVender = new javax.swing.JButton();
        comboFiltro = new javax.swing.JComboBox<>();

        radioTipo.setText("Tipo");
        radioTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioTipoActionPerformed(evt);
            }
        });

        radioMarca.setText("Marca");
        radioMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMarcaActionPerformed(evt);
            }
        });

        radioCategoria.setText("Categoria");
        radioCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioCategoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(radioTipo)
                .addGap(50, 50, 50)
                .addComponent(radioMarca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(radioCategoria)
                .addGap(46, 46, 46))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioTipo)
                    .addComponent(radioMarca)
                    .addComponent(radioCategoria))
                .addGap(0, 15, Short.MAX_VALUE))
        );

        botaofiltrar.setText("Filtrar");
        botaofiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaofiltrarActionPerformed(evt);
            }
        });

        tabelaVeiculosVender.setModel(telaVenderVenderVeiculoTableModel);
        jScrollPane1.setViewportView(tabelaVeiculosVender);

        botaoVender.setText("Vender");
        botaoVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVenderActionPerformed(evt);
            }
        });

        comboFiltro.setModel(new javax.swing.DefaultComboBoxModel<>());
        comboFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboFiltroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botaofiltrar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botaoVender, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comboFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(botaofiltrar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botaoVender)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void radioTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioTipoActionPerformed

        comboFiltro.removeAllItems();
        comboFiltro.addItem("Automóvel");
        comboFiltro.addItem("Motocicleta");
        comboFiltro.addItem("Van");

    }//GEN-LAST:event_radioTipoActionPerformed

    private void radioMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMarcaActionPerformed
        comboFiltro.removeAllItems();
        for (Marca a : Marca.values()) {
            comboFiltro.addItem(a.toString());
        }

    }//GEN-LAST:event_radioMarcaActionPerformed

    private void radioCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCategoriaActionPerformed
        comboFiltro.removeAllItems();
        for (Categoria a : Categoria.values()) {
            comboFiltro.addItem(a.toString());
        }
    }//GEN-LAST:event_radioCategoriaActionPerformed

    private void comboFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFiltroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboFiltroActionPerformed

    private void botaoVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVenderActionPerformed

        venderVeiculo();
    }//GEN-LAST:event_botaoVenderActionPerformed

    private void botaofiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaofiltrarActionPerformed
        try {
            executaFiltroTabela();
        } catch (Exception ex) {
            this.apresentaInfo("É necessário escolher um filtro!");
        }

    }//GEN-LAST:event_botaofiltrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoVender;
    private javax.swing.JButton botaofiltrar;
    private javax.swing.JComboBox<String> comboFiltro;
    private javax.swing.ButtonGroup grupoFiltroVeiculo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radioCategoria;
    private javax.swing.JRadioButton radioMarca;
    private javax.swing.JRadioButton radioTipo;
    private javax.swing.JTable tabelaVeiculosVender;
    // End of variables declaration//GEN-END:variables

    private void executaFiltroTabela() {

        if (radioCategoria.isSelected()) {

            List<Veiculo> veiculosFiltrados = veiculoMemoria.getListaCategoria(Categoria.valueOf(comboFiltro.getSelectedItem().toString()));
            telaVenderVenderVeiculoTableModel.setListaVeiculos(veiculosFiltrados);
        } else if (radioMarca.isSelected()) {
            List<Veiculo> veiculosFiltrados = veiculoMemoria.getListaMarca(Marca.valueOf(comboFiltro.getSelectedItem().toString()));
            telaVenderVenderVeiculoTableModel.setListaVeiculos(veiculosFiltrados);
        } else if (radioTipo.isSelected()) {
            List<Veiculo> veiculosFiltrados;
            switch (comboFiltro.getSelectedItem().toString()) {
                case "Automóvel":
                    veiculosFiltrados = veiculoMemoria.getListaAutomovel();
                    telaVenderVenderVeiculoTableModel.setListaVeiculos(veiculosFiltrados);
                    break;
                case "Motocicleta":
                    veiculosFiltrados = veiculoMemoria.getListaMotocicleta();
                    telaVenderVenderVeiculoTableModel.setListaVeiculos(veiculosFiltrados);
                    break;
                case "Van":
                    veiculosFiltrados = veiculoMemoria.getListaVan();
                    telaVenderVenderVeiculoTableModel.setListaVeiculos(veiculosFiltrados);
                default:

            }
        }
    }

    private List<Veiculo> getVeiculosParaVender() {
        int[] linhasSelecionadas = tabelaVeiculosVender.getSelectedRows();
        List<Veiculo> listaDevolver = new ArrayList();
        for (int i = 0; i < linhasSelecionadas.length; i++) {
            Veiculo veiculo = telaVenderVenderVeiculoTableModel.getVeiculo(linhasSelecionadas[i]);
            listaDevolver.add(veiculo);
        }
        return listaDevolver;
    }

    private void venderVeiculo() {
        try {
            List<Veiculo> veiculosSelecionados = getVeiculosParaVender();
            veiculoMemoria.venderLista(veiculosSelecionados);
            telaVenderVenderVeiculoTableModel.removeVeiculos(veiculosSelecionados);
        } catch (Exception ex) {
            this.apresentaErro("Erro ao vender o veiculo!");
        }

    }

    //Métodos de mensagem
    public void apresentaErro(String erro) {
        JOptionPane.showMessageDialog(null, erro + "\n", "Erro", JOptionPane.ERROR_MESSAGE);
    }

    public void apresentaInfo(String info) {
        JOptionPane.showMessageDialog(null, info + "\n", "Informação", JOptionPane.INFORMATION_MESSAGE);
    }

}
