/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package trabalhofinalsemmvc.Veiculo;


import java.text.ParseException;
import javax.swing.text.MaskFormatter;
import trabalhofinalsemmvc.utils.Estado;
import trabalhofinalsemmvc.utils.Marca;
import utils.Categoria;
import utils.ModeloAutomovel;
import utils.ModeloMotocicleta;
import utils.ModeloVan;


/**
 *
 * @author junio
 */
public class TelaIncluirVeiculo extends javax.swing.JPanel {

    /**
     * Creates new form TelaIncluirVeiculo
     */
    VeiculoMemoria veiculoIncluir = new VeiculoMemoria();

    public TelaIncluirVeiculo() {

        initComponents();
        for (ModeloAutomovel a : ModeloAutomovel.values()) {
            modelo.addItem(a);
        }
        for (ModeloMotocicleta a : ModeloMotocicleta.values()) {
            modelo.addItem(a);
        }
        for (ModeloVan a : ModeloVan.values()) {
            modelo.addItem(a);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelPlaca = new javax.swing.JLabel();
        categoria = new javax.swing.JComboBox<>();
        labelModelo = new javax.swing.JLabel();
        marcas = new javax.swing.JComboBox<>();
        labelCategoria = new javax.swing.JLabel();
        labelMarca = new javax.swing.JLabel();
        labelValor = new javax.swing.JLabel();
        botaoCriar = new javax.swing.JButton();
        valorVarianteUm = new javax.swing.JLabel();
        valorVarianteDois = new javax.swing.JLabel();
        valorVarianteTres = new javax.swing.JLabel();
        modelo = new javax.swing.JComboBox<>();
        MaskFormatter valordeCompra = null;
        try {
            valordeCompra = new MaskFormatter("######.##");
        }
        catch (ParseException e) {
            System.out.println("Erro na conversao de mascara!! (valor) ");
        }
        valor = new javax.swing.JFormattedTextField(valordeCompra);
        MaskFormatter placaMasc = null;
        try {
            placaMasc = new MaskFormatter("UUU-####");
        }
        catch (ParseException e) {
            System.out.println("Erro na conversao de mascara!! (placa) ");
        }
        placa = new javax.swing.JFormattedTextField(placaMasc);
        MaskFormatter anoMask = null;
        try {
            anoMask = new MaskFormatter("####");
        }
        catch (ParseException e) {
            System.out.println("Erro na conversao de mascara!! (ano) ");
        }
        ano = new javax.swing.JFormattedTextField(anoMask);

        jLabel1.setText("Ano");

        labelPlaca.setText("Placa");

        categoria.setModel(new javax.swing.DefaultComboBoxModel<>(Categoria.values()));
        categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriaActionPerformed(evt);
            }
        });

        labelModelo.setText("Modelo");

        marcas.setModel(new javax.swing.DefaultComboBoxModel<>(Marca.values()));
        marcas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marcasActionPerformed(evt);
            }
        });

        labelCategoria.setText("Categoria");

        labelMarca.setText("Marca");

        labelValor.setText("Valor de Compra");

        botaoCriar.setText("Incluir");
        botaoCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCriarActionPerformed(evt);
            }
        });

        modelo.setModel(new javax.swing.DefaultComboBoxModel<>());
        modelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeloActionPerformed(evt);
            }
        });

        placa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(botaoCriar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(valorVarianteUm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(valorVarianteDois, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelMarca)
                            .addComponent(labelCategoria)
                            .addComponent(labelModelo))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(marcas, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelValor)
                            .addComponent(labelPlaca)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(valorVarianteTres, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(placa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                .addComponent(valor, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMarca)
                    .addComponent(marcas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCategoria)
                    .addComponent(categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelModelo)
                    .addComponent(modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(valorVarianteUm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(valorVarianteDois)
                .addGap(18, 18, 18)
                .addComponent(valorVarianteTres)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelValor)
                    .addComponent(valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPlaca)
                    .addComponent(placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botaoCriar)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoriaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_categoriaActionPerformed

    private void marcasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marcasActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_marcasActionPerformed

    private void botaoCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCriarActionPerformed
        // TODO add your handling code here:
        getVeiculoFormulario();
        
    }//GEN-LAST:event_botaoCriarActionPerformed

    private void modeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeloActionPerformed
        // TODO add your handling code here:
        if (modelo.getSelectedItem() instanceof ModeloVan) {
            valorVarianteUm.setText("Popular: 200");
            valorVarianteDois.setText("Intermediario: 400");
            valorVarianteTres.setText("Luxo: 600");

        } else if (modelo.getSelectedItem() instanceof ModeloMotocicleta) {
            valorVarianteUm.setText("Popular: 70 ");
            valorVarianteDois.setText("Intermediario: 200 ");
            valorVarianteTres.setText("Luxo: 350 ");
        } else if (modelo.getSelectedItem() instanceof ModeloAutomovel) {
            valorVarianteUm.setText("Popular: 100");
            valorVarianteDois.setText("Intermediario: 300");
            valorVarianteTres.setText("Luxo: 450");
        }
    }//GEN-LAST:event_modeloActionPerformed

    private void placaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_placaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField ano;
    private javax.swing.JButton botaoCriar;
    private javax.swing.JComboBox<Categoria> categoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelCategoria;
    private javax.swing.JLabel labelMarca;
    private javax.swing.JLabel labelModelo;
    private javax.swing.JLabel labelPlaca;
    private javax.swing.JLabel labelValor;
    private javax.swing.JComboBox<Marca> marcas;
    private javax.swing.JComboBox<Enum> modelo;
    private javax.swing.JFormattedTextField placa;
    private javax.swing.JFormattedTextField valor;
    private javax.swing.JLabel valorVarianteDois;
    private javax.swing.JLabel valorVarianteTres;
    private javax.swing.JLabel valorVarianteUm;
    // End of variables declaration//GEN-END:variables
    public void getVeiculoFormulario() {
       Marca marcaVeiculo = (Marca)marcas.getSelectedItem();   
       Categoria categoriaVeiculo = (Categoria)categoria.getSelectedItem();
       Enum modeloVeiculo = (Enum)modelo.getSelectedItem();
       double valorDeCompraVeiculo = Double.parseDouble(valor.getText());
       String placaVeiculo = placa.getText();
       int anoVeiculo = Integer.parseInt(ano.getText());
       
       
       
        if (modeloVeiculo instanceof ModeloVan )  {
            veiculoIncluir.inserir(new Van(valorDeCompraVeiculo, placaVeiculo, anoVeiculo, Estado.DISPONIVEL, marcaVeiculo, categoriaVeiculo, (ModeloVan)modeloVeiculo));     
        }
        else if (modeloVeiculo instanceof ModeloMotocicleta) {
            veiculoIncluir.inserir(new Motocicleta(valorDeCompraVeiculo, placaVeiculo, anoVeiculo, Estado.DISPONIVEL, marcaVeiculo, categoriaVeiculo, (ModeloMotocicleta)modeloVeiculo));             
        }
        else {
            veiculoIncluir.inserir(new Automovel(valorDeCompraVeiculo, placaVeiculo, anoVeiculo, Estado.DISPONIVEL, marcaVeiculo, categoriaVeiculo, (ModeloAutomovel)modeloVeiculo));
        }
       
      
}
     

}
