/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package trabalhofinalsemmvc.Veiculo;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author eduar
 */
public class TelaDevolverVeiculo extends javax.swing.JPanel {
    private final TelaDevolverVeiculosTableModel devolverVeiculoTableModel = new TelaDevolverVeiculosTableModel();
    private VeiculoMemoria veiculoMemoria = new VeiculoMemoria();
    
    /** Creates new form TelaDevolverVeiculo */
    public TelaDevolverVeiculo() {
        initComponents();
        botaoDevolver.addActionListener(e -> devolverVeiculo());
        botaoListar.addActionListener(e -> listarVeiculosLocados());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaDevolverVeiculoFrame = new javax.swing.JTable();
        botaoListar = new javax.swing.JButton();
        botaoDevolver = new javax.swing.JButton();

        tabelaDevolverVeiculoFrame.setModel(devolverVeiculoTableModel);
        jScrollPane1.setViewportView(tabelaDevolverVeiculoFrame);

        botaoListar.setText("Listar");
        botaoListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoListarActionPerformed(evt);
            }
        });

        botaoDevolver.setText("Devolver");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoListar)
                .addGap(33, 33, 33)
                .addComponent(botaoDevolver)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoListar)
                    .addComponent(botaoDevolver))
                .addGap(0, 105, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botaoListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoListarActionPerformed
        // TODO add your handling code here:
        for (Veiculo veiculoTeste : veiculoMemoria.getLista())
        System.out.println(veiculoTeste.getMarca());
    }//GEN-LAST:event_botaoListarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoDevolver;
    private javax.swing.JButton botaoListar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaDevolverVeiculoFrame;
    // End of variables declaration//GEN-END:variables

    public void listarVeiculosLocados() {
        try{
            List<Veiculo> lista = veiculoMemoria.getListaLocados();
            devolverVeiculoTableModel.setListaVeiculos(lista);
        }catch(Exception ex){
            this.apresentaErro("Erro ao listar Veiculos.");
        }
    }
    
    public void devolverVeiculo(){
        try{
            List<Veiculo> listaParaDevolver = this.getVeiculoParaDevolver();
            veiculoMemoria.devolverLista(listaParaDevolver);
            listarVeiculosLocados();
        }catch(Exception ex){
            this.apresentaErro("Erro ao devolver Veículo.");
        }
    }
    
    private List<Veiculo> getVeiculoParaDevolver() {
        int[] linhasSelecionadas = tabelaDevolverVeiculoFrame.getSelectedRows();
        List<Veiculo> listaDevolver = new ArrayList();
        for (int i = 0; i < linhasSelecionadas.length; i++) {
            Veiculo veiculo = devolverVeiculoTableModel.getVeiculo(linhasSelecionadas[i]);
            listaDevolver.add(veiculo);
        }
        return listaDevolver;
    }
    
    //Métodos de mensagem
    public void apresentaErro(String erro) {
        JOptionPane.showMessageDialog(null,erro + "\n", "Erro", JOptionPane.ERROR_MESSAGE);
    }
    
    public void apresentaInfo(String info) {
        JOptionPane.showMessageDialog(null,info + "\n", "Informação", JOptionPane.INFORMATION_MESSAGE);
    }

    
}
