/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trabalhofinalsemmvc;

import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author eduar
 */
public class ProgramaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form ProgramaPrincipal
     */
    public ProgramaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        telaCliente1 = new trabalhofinalsemmvc.Cliente.TelaCliente();
        telaIncluirVeiculo1 = new trabalhofinalsemmvc.Veiculo.TelaIncluirVeiculo();
        telaLocarVeiculo1 = new trabalhofinalsemmvc.Veiculo.TelaLocarVeiculo();
        telaDevolverVeiculo1 = new trabalhofinalsemmvc.Veiculo.TelaDevolverVeiculo();
        telaVenderVeiculo1 = new trabalhofinalsemmvc.Veiculo.TelaVenderVeiculo();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addTab("Cliente", telaCliente1);
        jTabbedPane1.addTab("Incluir Veículo", telaIncluirVeiculo1);
        jTabbedPane1.addTab("Locar Veículo", telaLocarVeiculo1);
        jTabbedPane1.addTab("Devolver Veículo", telaDevolverVeiculo1);
        jTabbedPane1.addTab("Vender Veículo", telaVenderVeiculo1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProgramaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProgramaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProgramaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProgramaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProgramaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    private trabalhofinalsemmvc.Cliente.TelaCliente telaCliente1;
    private trabalhofinalsemmvc.Veiculo.TelaDevolverVeiculo telaDevolverVeiculo1;
    private trabalhofinalsemmvc.Veiculo.TelaIncluirVeiculo telaIncluirVeiculo1;
    private trabalhofinalsemmvc.Veiculo.TelaLocarVeiculo telaLocarVeiculo1;
    private trabalhofinalsemmvc.Veiculo.TelaVenderVeiculo telaVenderVeiculo1;
    // End of variables declaration//GEN-END:variables
}
